projects:
  hashtagHotline:
    schemaPath: amplify/backend/api/hashtagHotline/build/schema.graphql
    includes:
      - src/graphql/query.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
