// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6d5f05bd-739e-4231-b753-5e6567936bd9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_R8aZV80m2",
    "aws_user_pools_web_client_id": "7ack4f8tffbsga6b2tf8srfbj4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ymu4b2qt6jauxbz6rvm62ikfzy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yd3he6jnqzfl7d4pwrkv3243p4"
};


export default awsmobile;
